### ISSUE TITLE
MakeFiles 

### ISSUE THREAD

**Issue by gregtampa** [legitbs/quals-2014#1]
was trying to compile https://github.com/legitbs/quals-2014/blob/master/100Lines/100lines_LBS.c
got some errors.. about 'delete' undeclared 50:2
and some others. didnt see a makefile inside this..
using gcc -o 
gcc --version
gcc (Debian 6.3.0-18) 6.3.0 20170516 
on Kali

**Comment by gynophage** [comment]
Use g++.
