### ISSUE TITLE
running inside netcat

### ISSUE THREAD

**Issue by gregtampa** [legitbs/quals-2014#2]
how would run these to allow players to multi connect using netcat.
i tried netcat -lvp 1234 -e 3dttt
for example.. but it stops/closes once a player disconnects and also only allows one connection.
is there some script that launches them into a netcat listener?

thanks for your help, im not so good with using netcat. I figure there has to be a program that runs them. If you able to point me in right direction.

**Comment by gregtampa** [comment]
tcpserver -v -RHl0 0 1234 /home/ctf/quals-2014/3dttt/3dttt

**Comment by gynophage** [comment]
nc-k

Or use xinetd. That’s what we use.
